// Export for model
export * from "./IAccount";
export * from "./IAccountGroup";
export * from "./ICollaborator";
export * from "./IEmployee";
export * from "./IFeature";
export * from "./IGroupValue";
export * from "./IMenu";
export * from "./IMasterValue";
export * from "./IResource";
