name: Publish halato's npm packages
on:
  push:
    branches: [main]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-name: [user]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: ${{ secrets.NPM_REGISTRY_URL }}
      - name: build
        run: |
          npm ci
          npm run build
        working-directory: "lib/npm/${{ matrix.package-name }}"
      - name: publish
        run: |
          PUBLISHED=$(npm view | grep latest)
          LOCAL=$(cat package.json | grep version)
          echo ${PUBLISHED:27}
          echo ${LOCAL:16:-2}
          if [ "${PUBLISHED:27}" == "${LOCAL:16:-2}" ]; then
            exit 0
          fi
          npm publish
        working-directory: "lib/npm/${{ matrix.package-name }}"
