export const ACTIONS = {
  KSHT: {
    GET: "get",
    GET_LIST: "get_ksht_list",
    GET_FOR_OTHER_LIST: "get_for_other_list",
    CREATE: "create",
    UPDATE: "update",
    SUBMIT: "submit",
    APPROVE: "approve",
    REJECT: "reject",
    DELETE: "delete",
    RESTORE: "restore",
    ENABLE_ASSIGNEE: "enable_assignee",
  },
  TDHT: {
    GET: "get",
    GET_LIST: "get_tdht_list",
    GET_FOR_OTHER_LIST: "get_for_other_list",
    CREATE: "create",
    UPDATE: "update",
    FINISH: "finish",
    SUBMIT: "submit",
    APPROVE: "approve",
    REJECT: "reject",
    DELETE: "delete",
    RESTORE: "restore",
    ENABLE_ASSIGNEE: "enable_assignee",
  },
  KSUT: {
    GET: "get",
    GET_LIST: "get_ksut_list",
    GET_FOR_OTHER_LIST: "get_for_other_list",
    CREATE: "create",
    UPDATE: "update",
    SUBMIT: "submit",
    APPROVE: "approve",
    REJECT: "reject",
    DELETE: "delete",
    RESTORE: "restore",
    ENABLE_ASSIGNEE: "enable_assignee",
  },
  HQDT: {
    GET: "get",
    GET_LIST: "get_list",
    GET_FOR_OTHER_LIST: "get_for_other_list",
    CREATE: "create",
    UPDATE: "update",
    SUBMIT: "submit",
    APPROVE: "approve",
    REJECT: "reject",
    DELETE: "delete",
    RESTORE: "restore",
    ENABLE_ASSIGNEE: "enable_assignee",
  },
  PADT: {
    GET: "get",
    GET_LIST: "get_list",
    GET_FOR_OTHER_LIST: "get_for_other_list",
    CREATE: "create",
    UPDATE: "update",
    SUBMIT: "submit",
    APPROVE: "approve",
    REJECT: "reject",
    DELETE: "delete",
    RESTORE: "restore",
    ENABLE_ASSIGNEE: "enable_assignee",
  },
  TDUT: {
    GET: "get",
    GET_LIST: "get_tdut_list",
    GET_FOR_OTHER_LIST: "get_for_other_list",
    CREATE: "create",
    UPDATE: "update",
    FINISH: "finish",
    SUBMIT: "submit",
    APPROVE: "approve",
    REJECT: "reject",
    DELETE: "delete",
    RESTORE: "restore",
    ENABLE_ASSIGNEE: "enable_assignee",
  },
  TLDA: {
    GET: "get",
    GET_LIST: "get_list",
    GET_FOR_OTHER_LIST: "get_for_other_list",
    CREATE: "create",
    UPDATE: "update",
    SUBMIT: "submit",
    APPROVE: "approve",
    REJECT: "reject",
    DELETE: "delete",
    RESTORE: "restore",
    UPDATE_REF_INFO: "update_ref_info",
    UPDATE_PLAN_STEP: "update_plan_step",
    UPDATE_ACTION: "update_action",
    UPDATE_OPINION: "update_opinion",
  },
  NTK: {
    DELETE: "delete",
  },
} as const;
