FROM node:14-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci
COPY tsconfig*.json ./
COPY src ./src/
COPY migrations ./migrations/
RUN chown node:node .
USER node
COPY abac.conf ./abac.conf
ENTRYPOINT ["npm", "run"]
CMD ["typeorm", "migration:run"]

