export const NOTIFICATION = {
  BDS: {
    LUU: "bds.luu",
    GUI_DUYET: "bds.gui_duyet",
    PHE_DUYET: "bds.phe_duyet",
    TU_CHOI: "bds.tu_choi",
    YEU_CAU_DINH_GIA: "bds.yeu_cau_dinh_gia",
    TIEP_NHAN: "bds.tiep_nhan",
    CAP_NHAT_NGUON_TIN: "bds.cap_nhat_nguon_tin",
    DA_GIAO_DICH: "bds.da_giao_dich",
    CAP_NHAT_GIA_BAN: "bds.cap_nhat_gia_ban",
    XOA_NHAP: "bds.xoa_nhap",
    XOA_DA_DUYET: "bds.xoa_da_duyet",
    DA_MUA: "bds.da_mua",
    DA_BAN: "bds.da_ban",
  },
  KH: {
    LUU: "kh.luu",
    GUI_DUYET: "kh.gui_duyet",
    PHE_DUYET: "kh.phe_duyet",
    TU_CHOI: "kh.tu_choi",
    CAP_NHAT_NGUOI_THUC_HIEN: "kh.cap_nhat_nguoi_thuc_hien",
    XOA_DA_DUYET: "kh.xoa_da_duyet",
  },
  TH: {
    LUU: "th.luu",
    GUI_DUYET: "th.gui_duyet",
    PHE_DUYET: "th.phe_duyet",
    TU_CHOI: "th.tu_choi",
    TU_CHOI_HOAN_THANH: "th.tu_choi_hoan_thanh",
    TU_CHOI_GUI_DUYET: "th.tu_choi_goi_duyet",
    CAP_NHAT_NGUOI_THUC_HIEN: "th.cap_nhat_nguoi_thuc_hien",
    XOA_DA_DUYET: "th.xoa_da_duyet",
    HOAN_THANH: "th.hoan_thanh",
  },
  KU: {
    LUU: "ku.luu",
    GUI_DUYET: "ku.gui_duyet",
    PHE_DUYET: "ku.phe_duyet",
    TU_CHOI: "ku.tu_choi",
    CAP_NHAT_NGUOI_THUC_HIEN: "ku.cap_nhat_nguoi_thuc_hien",
    XOA_DA_DUYET: "ku.xoa_da_duyet",
  },
  HD: {
    LUU: "hd.luu",
    GUI_DUYET: "hd.gui_duyet",
    PHE_DUYET: "hd.phe_duyet",
    TU_CHOI: "hd.tu_choi",
    CAP_NHAT_NGUOI_THUC_HIEN: "hd.cap_nhat_nguoi_thuc_hien",
    XOA_DA_DUYET: "hd.xoa_da_duyet",
  },
  PD: {
    GUI_DUYET: "pd.gui_duyet",
    PHE_DUYET: "pd.phe_duyet",
    TU_CHOI: "pd.tu_choi",
    XOA_DA_DUYET: "pd.xoa_da_duyet",
  },
  TU: {
    LUU: "tu.luu",
    GUI_DUYET: "tu.gui_duyet",
    PHE_DUYET: "tu.phe_duyet",
    TU_CHOI_HOAN_THANH: "tu.tu_choi_hoan_thanh",
    TU_CHOI_GUI_DUYET: "tu.tu_choi_gui_duyet",
    CAP_NHAT_NGUOI_THUC_HIEN: "tu.cap_nhat_nguoi_thuc_hien",
    XOA_DA_DUYET: "tu.xoa_da_duyet",
    HOAN_THANH: "tu.hoan_thanh",
  },
  TL: {
    LUU: "tl.luu",
    GUI_DUYET: "tl.gui_duyet",
    PHE_DUYET: "tl.phe_duyet",
    TU_CHOI: "tl.tu_choi",
    XOA_DA_DUYET: "tl.xoa_da_duyet",
    LUU_Y_KIEN_QUAN_LY: "tl.luu_y_kien_quan_ly",
  }
} as const;
